<?php 
    session_start();

    if (isset($_SESSION["status"]) && $_SESSION["status"] == 1)
    {
        if (isset($_SESSION["role"]) && $_SESSION["role"] == 1)
        {
            include("../../includes/config.php");
            include("../../includes/functions.php");

            // initialize variables
            $roles = [];

            // connect to the database
            $conn = mysqli_connect(DATABASE_HOST, DATABASE_USER, DATABASE_PASS, DATABASE_NAME);

            // get all roles
            $getRoles = mysqli_query($conn, "SELECT * FROM roles ORDER BY name ASC");
            if (mysqli_num_rows($getRoles) > 0) // roles found
            {
                // for each role, get the necessary data to be displayed
                while ($role = mysqli_fetch_array($getRoles))
                {
                    // store permission group details locally
                    $role_id = $role["id"];
                    $role_name = $role["name"];
                    $default_generated = $role["default_generated"];

                    // get the number of users assigned to the role
                    $role_count = 0; // initialize role count to 0 by default
                    $getRoleCount = mysqli_prepare($conn, "SELECT id FROM users WHERE role_id=?");
                    mysqli_stmt_bind_param($getRoleCount, "i", $role_id);
                    if (mysqli_stmt_execute($getRoleCount))
                    {
                        $getRoleCountResult = mysqli_stmt_get_result($getRoleCount);
                        $role_count = mysqli_num_rows($getRoleCountResult);
                    }

                    // build the "Role Users" column
                    if ($role_count > 0) { $role_users = "<button class='btn btn-secondary w-100' onclick='getViewRoleUsersModal(".$role_id.");'>View ".$role_count." users</button>"; }
                    else { $role_users = "<button class='btn btn-secondary w-100' disabled>".$role_count." users</button>"; }

                    // build the actions column
                    $actions = "<div class='row justify-content-center float-end pe-4'>";
                    // build actions based on roles that are generated by default
                    if ($default_generated == 1)
                    {
                        $actions .= "<div class='p-1'><button class='btn btn-primary w-100' type='button' onclick='getEditRoleModal(".$role_id.");'><i class='fa-solid fa-eye'></i></button></div>";
                    }
                    // build actions for custom roles
                    else
                    {
                        $actions .= "<div class='p-1'><button class='btn btn-primary w-100' type='button' onclick='getEditRoleModal(".$role_id.");'><i class='fa-solid fa-pencil'></i></button></div>";
                    }
                    $actions .= "</div>";

                    // build the temporary array to store role data
                    $temp = [];
                    $temp["role_id"] = $role_id;
                    $temp["role_name"] = $role_name;
                    $temp["role_users"] = $role_users;
                    $temp["default_generated"] = $default_generated;
                    $temp["actions"] = $actions;

                    // add the temporary array to the master array
                    $roles[] = $temp;
                }
            }

            // disconnect from the database
            mysqli_close($conn);

            // send data to be printed
            $fullData = [];
            $fullData["draw"] = 1;
            $fullData["data"] = $roles;
            echo json_encode($fullData);
        }
    }
?>